author:
  email: null
  name: An Author
  twitter: null
  url: null
baseurl: /tate-lear-demo
collections:
  annotations:
    output: true
    permalink: /annotations/:path/
  volume_pages:
    output: true
    permalink: /pages/:path/
defaults:
- scope:
    path: ''
    type: volume_pages
  values:
    extra_js:
    - deepzoom.js
    - openseadragon.min.js
    - volume-page.js
    - hammer.min.js
    layout: volume_page
    short_label: p.
- scope:
    path: ''
    type: annotations
  values:
    layout: annotation
description: An annotated digital edition created with <a href="http://readux.library.emory.edu/">Readux</a>
homepage_image: http://digital.library.wayne.edu/readux/books/wayne:tatelear_Readux_VirtualVolume/pages/wayne:tatelear_Readux_VirtualPage_1/single-page/
image_size:
  page:
    height: 1000
    width: 665
  small-thumbnail:
    height: 100
    width: 66
  thumbnail:
    height: 300
    width: 199
permalink: pretty
publication_info:
  author: null
  date: '2016'
  editors:
  - Graham Hukill
  tei_xml: tei.xml
  title: 'The History of King Lear,: a tragedy, acted at the King''s-Theatre, reviv''d
    with alterations, an annotated digital edition'
show_annotation_author: true
source_info:
  author: null
  date: '1736'
  pdf_url: http://digital.library.wayne.edu/readux/books/wayne:tatelear_Readux_VirtualVolume/pdf/
  title: 'The History of King Lear,: a tragedy, acted at the King''s-Theatre, reviv''d
    with alterations'
  url: http://digital.library.wayne.edu/readux/books/wayne:tatelear_Readux_VirtualVolume/
  via_readux: true
tagline: ', an annotated digital edition'
title: 'The History of King Lear,: a tragedy, acted at the King''s-Theatre, reviv''d
  with alterations'
url: http://ghukill.github.io
version: 0.6
